<?php
/**
 * @category  Category Slider
 * @package   SD_CategorySlider
 * @author    Developer SD
 */

$blockObj= $block->getLayout()->createBlock('SD\CategorySlider\Block\CurrentCate');
$subcats = $blockObj->getCurrentCategory();
$mainCat = $blockObj->categoryDetail()->load($blockObj->getMainCategory()->getId());
$isSliderActivate = $mainCat->getSubcategorySlider();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<style>
.category-slider{position: relative;}
</style>
<?php $loaderHelper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\ImageLoader'); ?>
<div class="preload" style="position:absolute;z-index:4;background:#fff;width: 100%;text-align: center;height:100%">
    <img src="<?php echo $block->getViewFileUrl('SD_CategorySlider::images/loader.gif'); ?>" style="width:30px;margin-top:5%"/>
</div>
    <?php if ($subcats && $isSliderActivate == '1') { ?>
         <ul id="category-slider">
        <?php
        foreach ($subcats as $subcat) {
            if ($subcat->getIsActive()) {
                $_category = $blockObj->categoryDetail()->load($subcat->getId());
                $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
                $subcaturl = $subcat->getUrl();
                $bgColor = $_category->getBackgroundColour();

                $_imgHtml = '';
                ///if ($_imgUrl = $_category->getImageUrl('thumbnail')) {

                    $_imgUrl = $_category->getImageUrl('thumbnail');
                    // $_imgHtml = '<img loading="lazy" alt="" src="' . $_imgUrl . '" />';
                    $_title = '<h4>'.$subcat->getName().'</h4>';
                    //$_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');


                    if ($_imgUrl) {
                        $_imgHtml = 'data-src="'.$_imgUrl.'"';
                        $imgBgColor = '';
                        $class = 'class="owl-lazy"';
                    } else {
                        $_imgHtml = '';
                        $imgBgColor = 'background-color:'.$bgColor;
                        $class = '';
                    }


                    /* @escapeNotVerified */
                    echo '<li '.$class.' style="height: 160px;'.$imgBgColor.'" '.$_imgHtml.'>
                    <a style="width: inherit; height: inherit; display: block;" href="' . $subcaturl . '
                " class="block-promo" title="' . $subcat->getName() . '">
                ' . $_title . '

                </a></li>';

                //}
            }
        } ?>
    </ul>
    <?php } ?>
<script type="text/javascript">
    require(['jquery', 'owl_carousel'], function ($) {
        $(document).ready(function () {
            $(".preload").fadeOut(2000, function() { });
            $('#category-slider').owlCarousel({
                loop: true,
                margin: 10,
                nav: true,
                dots: false,
                lazyLoad: true,
                responsive:{
                    0:{
                        items:2
                    },
                    600:{
                        items:3
                    },
                    1000:{
                        items:4
                    }
                }
            });
        });


    });
</script>
